include_guard()

# SIMD optimizations based on CPU type and availability
include(CheckCXXCompilerFlag)

if (MSVC)
    add_definitions(-D_HAS_STD_BYTE=0)
    
    # Base optimizations for Visual Studio
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2 /GL")
    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /O2 /GL")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /LTCG")
    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LTCG")
    set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS_RELEASE} /LTCG")
    
    # Architecture-specific optimizations
    if(HD_CPU_OPTIMIZATION STREQUAL "AMD")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /Oi /Ot /Oy")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /Oi /Ot /Oy")
        message(STATUS "Enabling AMD-optimized build for MSVC")
    elseif(HD_CPU_OPTIMIZATION STREQUAL "INTEL")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /O2")
        message(STATUS "Enabling Intel-optimized build for MSVC")
    elseif(HD_CPU_OPTIMIZATION STREQUAL "ARM")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /O2")
        message(STATUS "Enabling ARM-optimized build for MSVC")
    elseif(HD_CPU_OPTIMIZATION STREQUAL "AUTO")
        # Auto-detect based on processor
        cmake_host_system_information(RESULT CPU_VENDOR QUERY PROCESSOR_DESCRIPTION)
        cmake_host_system_information(RESULT CPU_ARCH QUERY PROCESSOR_DESCRIPTION)
        if(CPU_ARCH MATCHES "arm" OR CPU_ARCH MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /O2")
            message(STATUS "Auto-detected ARM processor - enabling ARM optimizations")
        elseif(CPU_VENDOR MATCHES "AMD")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /Oi /Ot /Oy")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /Oi /Ot /Oy")
            message(STATUS "Auto-detected AMD processor - enabling AMD optimizations")
        else()
            message(STATUS "Auto-detected Intel/Generic processor - using conservative optimizations")
        endif()
    else()
        message(STATUS "Using generic optimizations for MSVC")
    endif()
else()
    # Architecture-specific optimizations for GCC/Clang
    if(HD_CPU_OPTIMIZATION STREQUAL "AMD")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=x86-64 -mtune=generic -DNDEBUG")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=x86-64 -mtune=generic -DNDEBUG")
        message(STATUS "Enabling AMD-optimized build for GCC/Clang")
    elseif(HD_CPU_OPTIMIZATION STREQUAL "INTEL")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2 -march=x86-64 -mtune=intel -DNDEBUG")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O2 -march=x86-64 -mtune=intel -DNDEBUG")
        message(STATUS "Enabling Intel-optimized build for GCC/Clang")
    elseif(HD_CPU_OPTIMIZATION STREQUAL "ARM")
        if(APPLE)
            # On Apple Silicon (macOS), compiler natively targets ARM64, no -march flag needed
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -DNDEBUG")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -DNDEBUG")
            message(STATUS "Enabling ARM64 native optimizations for Apple Silicon")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=armv8-a -DNDEBUG")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=armv8-a -DNDEBUG")
            message(STATUS "Enabling ARM64/AArch64 optimizations for GCC/Clang")
        else()
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=armv7-a -DNDEBUG")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=armv7-a -DNDEBUG")
            message(STATUS "Enabling ARM32 optimizations for GCC/Clang")
        endif()
    elseif(HD_CPU_OPTIMIZATION STREQUAL "AUTO")
        # Auto-detect based on processor
        cmake_host_system_information(RESULT CPU_VENDOR QUERY PROCESSOR_DESCRIPTION)
        if(APPLE AND (CMAKE_SYSTEM_PROCESSOR MATCHES "arm" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64" OR CPU_VENDOR MATCHES "Apple"))
            # On Apple Silicon (macOS), compiler natively targets ARM64, no -march flag needed
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -DNDEBUG")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -DNDEBUG")
            message(STATUS "Auto-detected Apple Silicon - enabling native ARM64 optimizations")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
                set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=armv8-a -DNDEBUG")
                set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=armv8-a -DNDEBUG")
                message(STATUS "Auto-detected ARM64 processor - enabling ARM optimizations")
            else()
                set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=armv7-a -DNDEBUG")
                set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=armv7-a -DNDEBUG")
                message(STATUS "Auto-detected ARM32 processor - enabling ARM optimizations")
            endif()
        elseif(CPU_VENDOR MATCHES "AMD")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=x86-64 -mtune=generic -DNDEBUG")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=x86-64 -mtune=generic -DNDEBUG")
            message(STATUS "Auto-detected AMD processor - enabling AMD optimizations")
        else()
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2 -march=x86-64 -mtune=intel -DNDEBUG")
            set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O2 -march=x86-64 -mtune=intel -DNDEBUG")
            message(STATUS "Auto-detected Intel/Generic processor - using Intel optimizations")
        endif()
    else()
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2 -march=x86-64 -DNDEBUG")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O2 -march=x86-64 -DNDEBUG")
        message(STATUS "Using generic optimizations for GCC/Clang")
    endif()
endif()

if (MSVC)
    if(HD_CPU_OPTIMIZATION STREQUAL "AMD_AVX512")
        check_cxx_compiler_flag("/arch:AVX512" HAS_AVX512)
        if(HAS_AVX512)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX512")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX512")
            message(STATUS "Enabling AVX-512 optimizations for AMD Zen 4+ processor (forced)")
            message(WARNING "AVX-512 support is limited to AMD Zen 4 (Ryzen 7000+) and later")
        else()
            message(WARNING "AVX-512 requested but not supported by compiler")
        endif()
    elseif(HD_CPU_OPTIMIZATION STREQUAL "AMD" OR (HD_CPU_OPTIMIZATION STREQUAL "AUTO" AND CPU_VENDOR MATCHES "AMD"))
        check_cxx_compiler_flag("/arch:AVX2" HAS_AVX2)
        if(HAS_AVX2)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX2")
            message(STATUS "Enabling AVX2 optimizations for AMD processor")
        endif() 
    elseif(HD_CPU_OPTIMIZATION STREQUAL "INTEL_AVX512")
        check_cxx_compiler_flag("/arch:AVX512" HAS_AVX512)
        if(HAS_AVX512)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX512")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX512")
            message(STATUS "Enabling AVX-512 optimizations for Intel processor (forced)")
            message(WARNING "AVX-512 may cause frequency throttling on some Intel CPUs. Use with caution.")
        else()
            message(WARNING "AVX-512 requested but not supported by compiler")
        endif()
    elseif(HD_CPU_OPTIMIZATION STREQUAL "INTEL" OR HD_CPU_OPTIMIZATION STREQUAL "AUTO" AND CPU_VENDOR MATCHES "Intel")
        check_cxx_compiler_flag("/arch:AVX2" HAS_AVX2)
        check_cxx_compiler_flag("/arch:AVX" HAS_AVX)
        
        if(HAS_AVX2)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX2")
            message(STATUS "Enabling AVX2 optimizations for Intel processor")
        elseif(HAS_AVX)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX")
            message(STATUS "Enabling AVX optimizations for Intel processor")
        endif()
        
        # Additional optimizations for Intel parallel execution
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Qpar /Qpar-report:1")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /favor:INTEL64")
        message(STATUS "Enabling Intel-specific parallel optimizations")
    endif()
    
    # For ARM CPUs, check for NEON support (if building with ARM toolchain)
    if(HD_CPU_OPTIMIZATION STREQUAL "ARM" OR (HD_CPU_OPTIMIZATION STREQUAL "AUTO" AND (CMAKE_SYSTEM_PROCESSOR MATCHES "arm" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")))
        # ARM NEON is implicit in ARM64, explicit check for ARM32
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
            message(STATUS "ARM64 detected - NEON optimizations enabled by default")
        else()
            check_cxx_compiler_flag("/arch:NEON" HAS_NEON)
            if(HAS_NEON)
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:NEON")
                set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:NEON")
                message(STATUS "Enabling NEON optimizations for ARM32 processor")
            endif()
        endif()
    endif()
else()
    # For GCC/Clang
    if(HD_CPU_OPTIMIZATION STREQUAL "AMD_AVX512")
        check_cxx_compiler_flag("-mavx512f" HAS_AVX512F)
        if(HAS_AVX512F)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx512f -mfma -mavx2")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx512f -mavx2")
            message(STATUS "Enabling AVX-512 optimizations for AMD Zen 4+ processor (forced)")
            message(WARNING "AVX-512 support is limited to AMD Zen 4 (Ryzen 7000+) and later")
        else()
            message(WARNING "AVX-512 requested but not supported by compiler")
        endif()
    elseif(HD_CPU_OPTIMIZATION STREQUAL "AMD" OR (HD_CPU_OPTIMIZATION STREQUAL "AUTO" AND CPU_VENDOR MATCHES "AMD"))
        check_cxx_compiler_flag("-mavx" HAS_AVX)
        check_cxx_compiler_flag("-mavx2" HAS_AVX2)
        if(HAS_AVX2)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx2")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx2")
            message(STATUS "Enabling AVX2 optimizations for AMD processor")
        elseif(HAS_AVX)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx")
            message(STATUS "Enabling AVX optimizations for AMD processor")
        endif()
    elseif(HD_CPU_OPTIMIZATION STREQUAL "INTEL_AVX512")
        check_cxx_compiler_flag("-mavx512f" HAS_AVX512F)
        if(HAS_AVX512F)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx512f -mfma -mavx2")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx512f -mavx2")
            message(STATUS "Enabling AVX-512 optimizations for Intel processor (forced)")
            message(WARNING "AVX-512 may cause frequency throttling on some Intel CPUs. Use with caution.")
        else()
            message(WARNING "AVX-512 requested but not supported by compiler")
        endif()
    elseif(HD_CPU_OPTIMIZATION STREQUAL "INTEL" OR (HD_CPU_OPTIMIZATION STREQUAL "AUTO" AND CPU_VENDOR MATCHES "Intel"))
        check_cxx_compiler_flag("-mavx" HAS_AVX)
        check_cxx_compiler_flag("-mavx2" HAS_AVX2)
    
        if(HAS_AVX2)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx2")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx2")
            message(STATUS "Enabling AVX2 optimizations for Intel processor")
        elseif(HAS_AVX)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx")
            message(STATUS "Enabling AVX optimizations for Intel processor")
        endif()
    endif()
    
    # For ARM CPUs, add NEON SIMD support
    if(HD_CPU_OPTIMIZATION STREQUAL "ARM" OR (HD_CPU_OPTIMIZATION STREQUAL "AUTO" AND (CMAKE_SYSTEM_PROCESSOR MATCHES "arm" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")))
        # ARM NEON optimizations
        check_cxx_compiler_flag("-mfpu=neon" HAS_NEON)
        if(HAS_NEON OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
                # ARM64 has NEON by default, add advanced SIMD optimizations
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a+simd")
                set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=armv8-a+simd")
                message(STATUS "Enabling Advanced SIMD (NEON) optimizations for ARM64 processor")
            else()
                # ARM32 explicit NEON
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mfpu=neon")
                set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mfpu=neon")
                message(STATUS "Enabling NEON optimizations for ARM32 processor")
            endif()
        endif()
    endif()
endif()