include_guard()

set(IMGUIZMO_LIBRARY_DIRECTORY ${EXTERNAL_LIBRARIES_DIRECTORY}/ImGuizmo)

set(IMGUIZMO_SOURCE_FILES
    ${IMGUIZMO_LIBRARY_DIRECTORY}/GraphEditor.cpp
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImCurveEdit.cpp
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImGradient.cpp
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImGuizmo.cpp
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImSequencer.cpp)

set(IMGUIZMO_HEADER_FILES
    ${IMGUIZMO_LIBRARY_DIRECTORY}/GraphEditor.h
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImCurveEdit.h
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImGradient.h
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImGuizmo.h
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImSequencer.h
    ${IMGUIZMO_LIBRARY_DIRECTORY}/ImZoomSlider.h)

set(IMGUIZMO_FILES ${IMGUIZMO_SOURCE_FILES} ${IMGUIZMO_HEADER_FILES})

add_library(imguizmo STATIC ${IMGUIZMO_FILES})
target_include_directories(
    imguizmo PRIVATE ${IMGUIZMO_LIBRARY_DIRECTORY}
    ${EXTERNAL_LIBRARIES_DIRECTORY}/imgui)
